### PR TITLE
Fix ""null" is not snowflake." error.

### PR DESCRIPTION
**Pull request by rhaym-tech**
This will fix the biggest dashboard eror:

DiscordAPIError[50035]: Invalid Form Body
user_id[NUMBER_TYPE_COERCE]: Value "null" is not snowflake

### CODE REVIEW

**Comment by cfmaniac** [comment]
I've TEsted this and Confirmed.

**Comment by LeGi0N09** [comment]
its not working

**Comment by LeGi0N09** [comment]
ERROR: Unhandled exception: Invalid Form Body
user_id[NUMBER_TYPE_COERCE]: Value "null" is not snowflake
new error

**Comment by cfmaniac** [comment]
> its not working

Did you pull the fix? 
in dashboard/routes/discord.js Line 68 change http:// to https://

**Comment by rhaym-tech** [comment]
To fix the snowflake issue
1- copy the change of pull request to target file
2- go to your mongo database and delete "session" section

**Review by cfmaniac — APPROVED** [review]

**Comment by LeGi0N09** [comment]
> To fix the snowflake issue 1- copy the change of pull request to target file 2- go to your mongo database and delete "session" section

HOW to do?

**Comment by rhaym-tech** [comment]
my man you're annoying asf

> > To fix the snowflake issue 1- copy the change of pull request to target file 2- go to your mongo database and delete "session" section
> 
> HOW to do?

1- go to your cluster => Database => Collections
image
2 - find "sessions" and click on the delete button
image

**Pull request merged**
