### PR TITLE
Changed BotStats

### PR DESCRIPTION
**Pull request by TenTraicion**
Added some new modules and changed Previous UI

Request to author: Kindly change the owner parameter and attach it with the .env file. These are out of my reach.

Thanks.

### CODE REVIEW

**Comment by saiteja-madha** [comment]
You mean move all the config.js values to .env or just the owner parameters?

**Comment by TenTraicion** [comment]
just the owner parameters.. ! it will help greatly

**Comment by saiteja-madha** [comment]
You may join the discord, we can help you there
https://discord.gg/fE75UShbqB

**Comment by TenTraicion** [comment]
Okay Thanks!

**Pull request closed without merging**
