### PR TITLE
Adds ChatGPT command Integration

### PR DESCRIPTION
**Pull request by N0rule**
Can be configured in config.js file
image

image

### CODE REVIEW

**Comment by rhaym-tech** [comment]
Since gpt-3.5 is paid, would you pay for it in order to add to Strange bot?, because martian won't do
and he already said that there's no point to add this feature here

**Comment by Legoman99573** [comment]
Fails to work with ``text-davinci-003`` model

**Comment by N0rule** [comment]
> Fails to work with `text-davinci-003` model

gpt-turbo uses chat/completions, and only compatible with them, it will not work with text-davinci-003, you need to rewrite code for it to work
image

**Comment by N0rule** [comment]
> Since gpt-3.5 is paid, would you pay for it in order to add to Strange bot?, because martian won't do and he already said that there's no point to add this feature here

it uses api keys, if someone will be interested, they can fork bot, add their api key, and use it for themself

**Comment by Legoman99573** [comment]
> > Fails to work with `text-davinci-003` model
> 
> gpt-turbo uses chat/completions, and only compatible with them, it will not work with text-davinci-003, you need to rewrite code for it to work image

I have forked it on my end and got it working for the older model. Only issues that arise is that jailbreaking works. Making it NSFW only should mitigate the damage of users who abuse it.

**Comment by N0rule** [comment]
> > > Fails to work with `text-davinci-003` model
> > 
> > gpt-turbo uses chat/completions, and only compatible with them, it will not work with text-davinci-003, you need to rewrite code for it to work image
> 
> I have forked it on my end and got it working for the older model. Only issues that arise is that jailbreaking works. Making it NSFW only should mitigate the damage of users who abuse it.

Yes,but newer chat models like gpt3turbo, is hardly jailbreakable, i tested it in 4000+ members server, for about a month or two, it's just says sorry, can't do that,so that should not be a problem

**Comment by Legoman99573** [comment]
> > > > Fails to work with `text-davinci-003` model
> > > 
> > > 
> > > gpt-turbo uses chat/completions, and only compatible with them, it will not work with text-davinci-003, you need to rewrite code for it to work image
> > 
> > 
> > I have forked it on my end and got it working for the older model. Only issues that arise is that jailbreaking works. Making it NSFW only should mitigate the damage of users who abuse it.
> 
> Yes,but newer chat models like gpt3turbo, is hardly jailbreakable, i tested it in 4000+ members server, for about a month or two, it's just says sorry, can't do that,so that should not be a problem

I know, but I am not paying for that model as I do not have the funds to use the newer model.

**Pull request closed without merging**
