### PR TITLE
Added Thumbnails and fixed Position in Queue

### PR DESCRIPTION
**Pull request by EdVoids**

### CODE REVIEW

**Comment by saiteja-madha** [comment]
@Jonathan5508 Could you please verify this?

**Comment by Jonathan5508** [comment]
@EdVoids the thumbnail does not set

**Comment by EdVoids** [comment]
It's works for Spotify and youtube, does not support in SoundCloud

**Comment by Jonathan5508** [comment]
Ok yes it does, and why not soundcloud? @EdVoids

**Pull request merged**
